### ISSUE TITLE
Limitation Aruco Markers

### ISSUE THREAD

**Issue by adlergfx** [okalachev/arucogen#15]
Hello, 

I like the marker generator and use it sometimes if i (again) lost my markers. I need a lot the 1001 standard aruco, which is my test marker. In the past everything was fine, but due to an update aruco is limited to 0-999 because the options tag contains no data-number attribute. Can you add it? As far as i know aruco uses 10 bits (thus 0-1023) so 1024 as data-number would be correct

Thanks for your work and time in the generator

**Comment by okalachev** [comment]
Hi, I checked the documentation, and found out, that the markers number in the original dictionary is indeed 1024, not 1000.

Thank you for finding such a huge issue. I guess it fixed now, can you please test?

The original dictionary is not used too often, so noone had found this issue before.

**Comment by adlergfx** [comment]
Works now as expected. Thank you for the fix!
