### ISSUE TITLE
why online generate marker are difference to opencv marker 

### ISSUE THREAD

**Issue by Chrislzy1993** [okalachev/arucogen#3]
hi, thanks for your great online aruco marker generator !  and i have a question,  when i generate 4x4 id= 0 marker , it show different from opencv same id marker, and i try other ,it is also differenct. so it is different dictionary ??? or how can i get the same marker with opencv 
https://docs.opencv.org/3.2.0/d5/dae/tutorial_aruco_detection.html
Thanks a lot

**Comment by okalachev** [comment]
Hello!

Should be the same! Please, show, what you get on the site and in OpenCV.

**Comment by Chrislzy1993** [comment]
@okalachev , thanks for your reply.  on opencv aruco tutorials,  the following aruco marker comes from cv::aruco::**DICT_6X6_250**. 
![image](https://user-images.githubusercontent.com/17810965/50440545-af439480-0931-11e9-98e9-e2f850e3bd1b.png)
we can see the marker id is: 203, 124, 23, 62, 98, 40
when i use online aruco generator to the same size and id marker, it look different of all:
![image](https://user-images.githubusercontent.com/17810965/50440670-3b55bc00-0932-11e9-96b2-aec22fdc17da.png)
![image](https://user-images.githubusercontent.com/17810965/50440685-47da1480-0932-11e9-8b68-6797f3f93b95.png)
![image](https://user-images.githubusercontent.com/17810965/50440698-54f70380-0932-11e9-9221-41699e1adfdc.png)
![image](https://user-images.githubusercontent.com/17810965/50440707-5e806b80-0932-11e9-8e6a-2b1889f034b3.png)
![image](https://user-images.githubusercontent.com/17810965/50440723-6cce8780-0932-11e9-8f2a-0eca9bb7b55c.png)
![image](https://user-images.githubusercontent.com/17810965/50440738-7952e000-0932-11e9-8cdc-2bf1d7a4689f.png)
thanks again, and please tell me where is wrong ??  hope for you reply!!!

**Comment by okalachev** [comment]
Maybe something wrong with the illustration in the OpenCV documentation?

I tried this code:

```python
import cv2
import cv2.aruco as aruco

d = aruco.getPredefinedDictionary(aruco.DICT_6X6_250)
cv2.imwrite('aruco-6x6-203.png', aruco.drawMarker(d, 203, 200))
```

And it gives the picture exactly like the generator:

![aruco-6x6-203](https://user-images.githubusercontent.com/1683279/50456149-9c49b800-0963-11e9-87c5-ba3ab1fa5037.png)

**Comment by okalachev** [comment]
@Chrislzy1993, is issue resolved? Can I close for now?

**Comment by Chrislzy1993** [comment]
thanks for you nice answer, happy new year!
