### ISSUE TITLE
Generated markers different from aruco dictionary...

### ISSUE THREAD

**Issue by ashenkin** [okalachev/arucogen#6]
Hi there,
I've seen this issue raised before, but i'm finding that the markers generated from your webpage are different than the arcuo 16h3 dict.  Here's your marker 0 versus the aruco marker 0 (note, this is the compiled aruco, not that from open cv).  Any thoughts?  One helpful thing would be to provide perhaps the dictionary that aruco can take on the command line?  You've referenced the .hpp, but i'm not sure how to make that readable from the command line... thanks!

yours: ![svgaruco0](https://user-images.githubusercontent.com/1608945/61642578-89882f00-ac77-11e9-91ae-1a15585aa97f.png)

aruco:![aruco_mip_16h3_00000](https://user-images.githubusercontent.com/1608945/61642590-90af3d00-ac77-11e9-96fa-d4872c5d730b.png)

**Comment by okalachev** [comment]
Where did you get ArUco library you use?
